feat: Hover support and partial completion support for C#
tris203/rzls.nvim pull request #4
Opened 2024-10-28 19:45 UTC by neubaner

This PR adds a lot of legwork to make the Razor LSP communicate with Roslyn correctly, hover support and partial completions for the C# portions of Razor file.

2024-10-28 21:25 UTC, tris203 requested changes
This looks awesome, thank you so much

2024-10-28 21:25 UTC, tris203 commented on lua/rzls/razor.lua
> +local nio = require("nio")
We should document the dependecy on `nvim-neotest/nvim-nio`

2024-10-28 21:25 UTC, tris203 commented on lua/rzls/razor.lua
> +end, {})
What is this doing?

2024-10-28 21:25 UTC, tris203 commented on lua/rzls/init.lua
> +                    rzlsconfig.path,
This is much better, thanks

2024-10-28 21:25 UTC, tris203 commented on lua/rzls/init.lua
> +end
Can this be pulled into a separate module?

2024-10-28 21:25 UTC, tris203 commented on lua/rzls/handlers/hover.lua
> +        assert(not err, err)
```suggestion
        assert(not err, vim.inspect(err))
```
err is a table, but assert wants a string as the error

2024-10-28 21:25 UTC, tris203 commented on lua/rzls/handlers/hover.lua
> +        local virtual_buf_client = nio.lsp.get_clients({ bufnr = virtual_bufnr })[1]
```suggestion
        local lspname = function(kind)
            if kind == 2 then
            return "html"
            elseif kind == 1 then
            return "roslyn"
            end
        end

        local virtual_buf_client = nio.lsp.get_clients({ bufnr = virtual_bufnr, name=lspname(language_query_response.kind) })[1]
```
can we put something like this in utils and then use it here

2024-10-28 21:25 UTC, tris203 commented on lua/rzls/handlers/init.lua
> -    ["razor/initialize"] = not_implemented,
i think we might need this method in future, can i stay as a place holder?

2024-10-29 18:18 UTC, gneubaner commented on lua/rzls/handlers/init.lua
> -    ["razor/initialize"] = not_implemented,
"razor/initialize" is actually a handler of the Roslyn LSP.

2024-10-29 18:18 UTC, neubaner commented on lua/rzls/handlers/init.lua
> -    ["razor/initialize"] = not_implemented,
"razor/initialize" is a handler for the Roslyn LSP.

2024-10-29 18:19 UTC, neubaner commented on lua/rzls/razor.lua
> +end, {})
It was leftover code, already got rid of it :)

2024-10-30 21:50 UTC, merged